const express=require("express"),multer=require("multer"),QRCode=require("qrcode"),fs=require("fs"),path=require("path"),crypto=require("crypto");
const app=express(),PORT=process.env.PORT||3000,DIR=path.join(__dirname,"data"),UP=path.join(DIR,"uploads"),DB=path.join(DIR,"pages.json");
fs.mkdirSync(UP,{recursive:true});if(!fs.existsSync(DB))fs.writeFileSync(DB,"{}");
app.use(express.json({limit:"3mb"}));app.use(express.urlencoded({extended:true}));app.use("/uploads",express.static(UP));app.use(express.static(path.join(__dirname,"public")));
const upload=multer({storage:multer.diskStorage({destination:UP,filename:(r,f,cb)=>cb(null,crypto.randomBytes(9).toString("hex")+path.extname(f.originalname))}),limits:{fileSize:8*1024*1024}});
const read=()=>JSON.parse(fs.readFileSync(DB));const write=x=>fs.writeFileSync(DB,JSON.stringify(x,null,2));
const clean=b=>({type:["birthday","proposal","valentine","anniversary","custom"].includes(b.type)?b.type:"birthday",recipient:String(b.recipient||"").slice(0,80),sender:String(b.sender||"").slice(0,80),title:String(b.title||"").slice(0,140),message:String(b.message||"").slice(0,5000),date:String(b.date||"").slice(0,40),accent:String(b.accent||"#ff4f81").slice(0,20),musicUrl:String(b.musicUrl||"").slice(0,500),proposalQuestion:String(b.proposalQuestion||"").slice(0,300),yesText:String(b.yesText||"Yes ❤️").slice(0,80),noText:String(b.noText||"Maybe 🙈").slice(0,80),sections:Array.isArray(b.sections)?b.sections.slice(0,8):[]});
app.get("/api/pages",(q,s)=>s.json(Object.values(read()).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))));
app.post("/api/pages",(q,s)=>{const d=read(),id=crypto.randomBytes(7).toString("base64url"),p=clean(q.body);d[id]={...p,id,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};write(d);s.json({id,url:`${q.protocol}://${q.get("host")}/s/${id}`})});
app.get("/api/pages/:id",(q,s)=>{const p=read()[q.params.id];p?s.json(p):s.status(404).json({error:"Not found"})});
app.put("/api/pages/:id",(q,s)=>{const d=read(),o=d[q.params.id];if(!o)return s.status(404).end();d[q.params.id]={...clean(q.body),id:q.params.id,createdAt:o.createdAt,updatedAt:new Date().toISOString()};write(d);s.json(d[q.params.id])});
app.delete("/api/pages/:id",(q,s)=>{const d=read();delete d[q.params.id];write(d);s.json({ok:true})});
app.post("/api/upload",upload.array("photos",8),(q,s)=>s.json({urls:(q.files||[]).map(f=>"/uploads/"+f.filename)}));
app.get("/api/pages/:id/qr",async(q,s)=>{if(!read()[q.params.id])return s.status(404).end();s.type("png").send(await QRCode.toBuffer(`${q.protocol}://${q.get("host")}/s/${q.params.id}`,{width:800,margin:2}))});
app.get("/s/:id",(q,s)=>s.sendFile(path.join(__dirname,"public","surprise.html")));
app.listen(PORT,()=>console.log("WishingStar on "+PORT));