const express=require("express"),QRCode=require("qrcode"),fs=require("fs"),path=require("path"),crypto=require("crypto");
const app=express(),PORT=process.env.PORT||3000,DB=path.join(__dirname,"data/pages.json");
fs.mkdirSync(path.dirname(DB),{recursive:true});if(!fs.existsSync(DB))fs.writeFileSync(DB,"{}");
app.use(express.json({limit:"15mb"}));app.use(express.static(path.join(__dirname,"public")));
const read=()=>JSON.parse(fs.readFileSync(DB,"utf8")),write=x=>fs.writeFileSync(DB,JSON.stringify(x,null,2));
const clean=b=>({type:["birthday","proposal","valentine","anniversary","custom"].includes(b.type)?b.type:"birthday",recipient:String(b.recipient||"").slice(0,80),sender:String(b.sender||"").slice(0,80),title:String(b.title||"").slice(0,140),message:String(b.message||"").slice(0,6000),date:String(b.date||"").slice(0,40),theme:["rose","lavender","midnight","sunset","classic"].includes(b.theme)?b.theme:"rose",accent:String(b.accent||"#ff4f81").slice(0,20),musicUrl:String(b.musicUrl||"").slice(0,500),proposalQuestion:String(b.proposalQuestion||"").slice(0,300),yesText:String(b.yesText||"Yes ❤️").slice(0,80),noText:String(b.noText||"Maybe 🙈").slice(0,80),photos:Array.isArray(b.photos)?b.photos.filter(x=>typeof x==="string"&&x.length<1500000).slice(0,8):[]});
app.get("/api/pages",(q,s)=>s.json(Object.values(read()).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))));
app.post("/api/pages",(q,s)=>{const d=read(),id=crypto.randomBytes(7).toString("base64url"),p=clean(q.body);d[id]={...p,id,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};write(d);s.json({id,url:`${q.protocol}://${q.get("host")}/s/${id}`})});
app.get("/api/pages/:id",(q,s)=>{const p=read()[q.params.id];p?s.json(p):s.status(404).json({error:"Not found"})});
app.put("/api/pages/:id",(q,s)=>{const d=read(),o=d[q.params.id];if(!o)return s.status(404).json({error:"Not found"});d[q.params.id]={...clean(q.body),id:q.params.id,createdAt:o.createdAt,updatedAt:new Date().toISOString()};write(d);s.json(d[q.params.id])});
app.delete("/api/pages/:id",(q,s)=>{const d=read();if(!d[q.params.id])return s.status(404).end();delete d[q.params.id];write(d);s.json({ok:true})});
app.get("/api/pages/:id/qr",async(q,s)=>{if(!read()[q.params.id])return s.status(404).end();s.type("png").send(await QRCode.toBuffer(`${q.protocol}://${q.get("host")}/s/${q.params.id}`,{width:900,margin:2,errorCorrectionLevel:"H"}))});
app.get("/s/:id",(q,s)=>s.sendFile(path.join(__dirname,"public/surprise.html")));
app.listen(PORT,()=>console.log("WishingStar v2 on "+PORT));